# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_created_date'),
        ('multichoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestion',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='point_value',
            field=models.IntegerField(),
        ),
    ]
