# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0002_auto_20161203_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestion',
            name='point_value',
            field=models.IntegerField(default=1),
        ),
    ]
