# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0003_auto_20161203_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcquestion',
            old_name='quiz',
            new_name='inquiz',
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
    ]
