# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer'),
        ('multichoice', '0005_auto_20161220_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Answer')),
                ('student_choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multichoice.MCQuestion')),
            ],
            bases=('quiz.answer',),
        ),
    ]
