# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created:'),
            preserve_default=False,
        ),
    ]
